### ISSUE TITLE
Move contributing process to CONTRIBUTING.md

### ISSUE THREAD

**Issue by Lacah** [ServiceNowDevProgram/ServiceNow-GenAi-Prompt-Library#7]
The CONTRIBUTING.md file does not provide enough details about how to actually contribute to this repo, only some guidelines. The actual, repo specific steps are in the README.md under the [Contributing Process](https://github.com/ServiceNowDevProgram/ServiceNow-GenAi-Prompt-Library?tab=readme-ov-file#contributing-process) section.
I suggest moving its contents into the CONTRIBUTING.md file, and linking to it from the existing readme section.

**Comment by tejasathalye** [comment]
hey @Lacah can you assign it to me? I will be working on it right away!

**Comment by Lacah** [comment]
Thanks @tejasathalye

**Comment by tejasathalye** [comment]
hey @Lacah , I had a doubt!
While creating the 'CONTRIBUTING.MD' file, do I have to make changes in the 'README.md'?

**Comment by tejasathalye** [comment]
hey @Lacah , I had a doubt!
While creating the `CONTRIBUTING.MD` file, do I have to make changes in the `README.md`?

**Comment by tejasathalye** [comment]
hey @Lacah Made the changes as promised! 
could you review and merge?
Thanks!
